publish_mode: editorial_workflow
backend:
  name: github
  auth_scope: repo
  repo: ProjectDrawdown/open-collaboratory
  open_authoring: true
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Description", name: "description", widget: "string" }
        - { label: "Link", name: "link", widget: "string"}
        - label: 'Projects'
          name: "projects"
          widget: "relation"
          collection: "projects"
          value_field: "{{fields.name}}_{{fields.description}}_{{fields.link}}"
          search_fields: ["name"]
          multiple: true
  - name: "projects"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    label: "Projects"
    folder: "projects"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string"}
      - { label: "Active", name: "acive", widget: "boolean"}
      - { label: "Description", name: "description", widget: "text"}
      - { label: "Link", name: "link", widget: "string"}
      - { label: "Collaborators", name: "collaborators", widget: "relation", collection: "authors", value_field: "name", search_fields: ["name"] }
  - name: "resources"
    label: "Resources"
    folder: "resources"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string"}
      - { label: "Description", name: "description", widget: "text"}
      - { label: "File", name: "file", widget: "file"}
      - { label: "Link", name: "link", widget: "string"}
      - label: 'Related Projects'
        name: "projects"
        widget: relation
        collection: "projects"
        value_field: "name"
        search_fields: ["name"]
        multiple: true
  - name: "authors"
    label: "Authors"
    folder: "authors"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string"}
      - { label: "Nickname", name: "nickname", widget: "string"}

