backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "pages"
    label: "Pages"
    files:
    - label: "Home"
      name: "home"
      file: "content/home.md"
      fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Description", name: "description", widget: "string" }
        - { label: "Link", name: "link", widget: "string"}
        - label: 'Projects'
          name: "projects"
          widget: relation
          collection: "project"
          value_field: "name"
          search_fields: ["name"]
          multiple: true
  - name: "projects"
    label: "Projects"
    folder: "_projects"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string"}
      - { label: "Description", name: "description", widget: "text"}
      - { label: "Link", name: "link", widget: "string"}
  - name: "resources"
    label: "Resources"
    folder: "_resources"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string"}
      - { label: "Description", name: "description", widget: "text"}
      - { label: "File", name: "file", widget: "file"}
      - { label: "Link", name: "link", widget: "string"}
      - label: 'Related Projects'
        name: "projects"
        widget: relation
        collection: "projects"
        value_field: "name"
        search_fields: ["name"]
        multiple: true

